import { useEffect, useState } from "react";
import { Pencil, Plus, Trash2, X } from "lucide-react";
import * as api from "@/lib/api";

const blank: api.TitleInput = { title: "", originalTitle: "", slug: "", description: "", type: "series", country: "Korea", year: 2024, status: "completed", rating: 0, poster: "", backdrop: "", language: "Korean", director: "", cast: [], trailer: null, genres: [] };
const field = "h-10 w-full border border-border bg-secondary px-3 text-sm outline-none focus:border-primary";
function Editor({ value, onSave, onClose }: { value: api.TitleInput; onSave: (v: api.TitleInput) => Promise<void>; onClose: () => void }) {
  const [form, setForm] = useState(value); const set = (key: keyof api.TitleInput, v: unknown) => setForm(x => ({ ...x, [key]: v }));
  return <div className="fixed inset-0 z-50 grid place-items-center bg-black/75 p-4"><form className="max-h-[92vh] w-full max-w-3xl overflow-auto border border-border bg-card p-6" onSubmit={e => { e.preventDefault(); void onSave(form); }} dir="rtl"><div className="flex justify-between"><h2 className="font-display text-3xl">إدارة عنوان</h2><button type="button" onClick={onClose}><X size={18}/></button></div><div className="mt-6 grid gap-3 sm:grid-cols-2">
    {([["title","العنوان"],["originalTitle","العنوان الأصلي"],["slug","Slug"],["director","المخرج"],["language","اللغة"],["poster","الملصق"],["backdrop","الخلفية"]] as const).map(([key,label]) => <label key={key} className="text-[10px] text-muted-foreground">{label}<input className={field} value={String(form[key] ?? "")} onChange={e => set(key, e.target.value)} /></label>)}
    <label className="text-[10px] text-muted-foreground">النوع<select className={field} value={form.type} onChange={e => set("type", e.target.value)}><option value="series">دراما</option><option value="movie">فيلم</option></select></label>
    <label className="text-[10px] text-muted-foreground">الحالة<select className={field} value={form.status} onChange={e => set("status", e.target.value)}><option value="upcoming">قريباً</option><option value="airing">يبث الآن</option><option value="completed">مكتمل</option></select></label>
    <label className="text-[10px] text-muted-foreground">السنة<input type="number" className={field} value={form.year} onChange={e => set("year", Number(e.target.value))}/></label>
    <label className="text-[10px] text-muted-foreground">التقييم<input type="number" step="0.1" className={field} value={form.rating} onChange={e => set("rating", Number(e.target.value))}/></label>
    <label className="text-[10px] text-muted-foreground">التصنيفات<textarea className={field} value={form.genres.join(", ")} onChange={e => set("genres", e.target.value.split(",").map(x => x.trim()).filter(Boolean))}/></label>
    <label className="text-[10px] text-muted-foreground">طاقم العمل<textarea className={field} value={form.cast.join(", ")} onChange={e => set("cast", e.target.value.split(",").map(x => x.trim()).filter(Boolean))}/></label>
    <label className="text-[10px] text-muted-foreground sm:col-span-2">الوصف<textarea className="min-h-28 w-full border border-border bg-secondary p-3 text-sm" value={form.description} onChange={e => set("description", e.target.value)}/></label>
  </div><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={onClose} className="border border-border px-4 py-2 text-xs">إلغاء</button><button className="bg-primary px-5 py-2 text-xs font-semibold text-primary-foreground">حفظ</button></div></form></div>;
}
function Details({ id, notice }: { id: string; notice: (s: string) => void }) {
  const [seasons, setSeasons] = useState<api.Season[]>([]); const [open, setOpen] = useState<string>(""); const [episodes, setEpisodes] = useState<api.Episode[]>([]); const [episode, setEpisode] = useState<string>(""); const [links, setLinks] = useState<api.WatchLink[]>([]); const [server, setServer] = useState({ name: "", url: "" });
  const load = () => api.listSeasons(id).then(setSeasons); useEffect(() => { void load(); }, [id]);
  return <div className="mt-4 border-t border-border pt-4 space-y-2"><button className="border border-border px-3 py-2 text-xs" onClick={() => void api.addSeason(id, seasons.length + 1).then(() => { void load(); notice("تمت إضافة الموسم"); })}><Plus size={13} className="inline"/> موسم</button>{seasons.map(s => <div key={s.id} className="border border-border p-3"><div className="flex justify-between text-sm"><button onClick={() => { setOpen(s.id); void api.listEpisodes(s.id).then(setEpisodes); }}>{s.title}</button><button onClick={() => void api.deleteSeason(s.id).then(() => { void load(); notice("تم حذف الموسم"); })}><Trash2 size={13}/></button></div>{open === s.id && <div className="mt-3 space-y-2"><div className="flex gap-2"><button className="border border-border px-2 text-xs" onClick={() => { const title = window.prompt("اسم الحلقة"); if (title) void api.addEpisode(s.id, episodes.length + 1, title).then(() => api.listEpisodes(s.id).then(setEpisodes)); }}>إضافة حلقة</button></div>{episodes.map(e => <div key={e.id} className="border-t border-border pt-2 text-xs"><div className="flex justify-between"><button onClick={() => { setEpisode(e.id); void api.listLinks(e.id).then(setLinks); }}>{e.episodeNumber}. {e.title}</button><button onClick={() => void api.deleteEpisode(e.id).then(() => api.listEpisodes(s.id).then(setEpisodes))}><Trash2 size={12}/></button></div>{episode === e.id && <div className="mt-2 flex flex-wrap gap-2"><input className={field} placeholder="اسم الخادم" value={server.name} onChange={x => setServer({ ...server, name: x.target.value })}/><input className={field} placeholder="https://..." value={server.url} onChange={x => setServer({ ...server, url: x.target.value })}/><button className="bg-primary px-3 text-xs text-primary-foreground" onClick={() => void api.addLink(e.id, server.name, server.url).then(() => api.listLinks(e.id).then(setLinks))}>إضافة رابط</button>{links.map(l => <div key={l.id} className="flex w-full justify-between border-t border-border py-1"><a href={l.url} target="_blank" rel="noreferrer" className="text-primary">{l.name}</a><button onClick={() => void api.deleteLink(l.id).then(() => api.listLinks(e.id).then(setLinks))}><Trash2 size={12}/></button></div>)}</div>}</div>)}</div>}</div>)}</div>;
}
export function AdminConsole() {
  const [user, setUser] = useState<api.AdminUser | null>(null); const [checking, setChecking] = useState(true); const [error, setError] = useState(""); const [titles, setTitles] = useState<api.ApiTitle[]>([]); const [overview, setOverview] = useState<api.Overview | null>(null); const [editing, setEditing] = useState<{ id?: string; value: api.TitleInput } | null>(null); const [expanded, setExpanded] = useState(""); const [search, setSearch] = useState("");
  const load = async () => { const [a, b] = await Promise.all([api.getOverview(), api.listAdminTitles()]); setOverview(a); setTitles(b.items); };
  useEffect(() => { api.getAdmin().then(x => { setUser(x); return load(); }).catch(() => undefined).finally(() => setChecking(false)); }, []);
  if (checking) return <div className="py-20 text-center text-sm text-muted-foreground">جارٍ التحقق…</div>;
  if (!user) return <form className="mx-auto mt-12 max-w-md border border-border bg-card p-6" dir="rtl" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); api.loginAdmin(String(f.get("email")), String(f.get("password"))).then(x => { setUser(x.user); void load(); }).catch(x => setError(x.message)); }}><h1 className="font-display text-3xl">دخول المدير</h1>{error && <p className="mt-3 text-xs text-primary">{error}</p>}<input name="email" type="email" autoComplete="username" required placeholder="البريد الإلكتروني" className={`${field} mt-6`}/><input name="password" type="password" autoComplete="current-password" required placeholder="كلمة المرور" className={`${field} mt-3`}/><button className="mt-4 h-11 w-full bg-primary text-xs font-semibold text-primary-foreground">دخول آمن</button></form>;
  const visible = titles.filter(x => `${x.title} ${x.country}`.toLowerCase().includes(search.toLowerCase()));
  return <div dir="rtl"><div className="flex flex-wrap items-end justify-between gap-4 border-b border-border pb-8"><div><p className="font-mono-ui text-[10px] text-primary">ASIAN SCREEN / ADMIN</p><h1 className="mt-3 font-display text-5xl">غرفة الكتالوج</h1><p className="mt-2 text-xs text-muted-foreground">{user.email}</p></div><div className="flex gap-2"><button className="bg-primary px-4 py-2 text-xs text-primary-foreground" onClick={() => setEditing({ value: { ...blank, slug: `title-${Date.now()}` } })}><Plus size={14} className="inline"/> عنوان جديد</button><button className="border border-border px-4 py-2 text-xs" onClick={() => void api.logoutAdmin().then(() => setUser(null))}>خروج</button></div></div>{overview && <div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4 lg:grid-cols-8">{Object.entries(overview).map(([k,v]) => <div key={k} className="border border-border bg-card p-3"><div className="font-mono-ui text-xl text-accent">{v}</div><div className="mt-1 text-[10px] text-muted-foreground">{k}</div></div>)}</div>}<div className="mt-6 flex gap-3"><input className={`${field} max-w-sm`} placeholder="بحث…" value={search} onChange={e => setSearch(e.target.value)}/><span className="self-center text-xs text-muted-foreground">{visible.length} عنوان</span></div><div className="mt-4 overflow-x-auto border border-border"><table className="w-full min-w-[760px] text-right text-sm"><thead className="bg-secondary text-xs"><tr><th className="p-3">العنوان</th><th>النوع</th><th>البلد</th><th>السنة</th><th>الحالة</th><th>إجراءات</th></tr></thead><tbody>{visible.map(x => <tr key={x.id} className="border-t border-border"><td className="p-3">{x.title}<small className="block text-muted-foreground">{x.originalTitle}</small></td><td>{x.type}</td><td>{x.country}</td><td>{x.year}</td><td className="text-primary">{x.status}</td><td className="p-3"><button onClick={() => setEditing({ id: x.id, value: { ...x, originalTitle: x.originalTitle ?? "", trailer: x.trailer ?? "" } })}><Pencil size={14}/></button><button className="mr-3" onClick={() => window.confirm("حذف العنوان؟") && void api.deleteTitle(x.id).then(load)}><Trash2 size={14}/></button>{x.type === "series" && <button className="mr-3 text-primary" onClick={() => setExpanded(expanded === x.id ? "" : x.id)}>المواسم</button>}{expanded === x.id && <Details id={x.id} notice={setError}/>}</td></tr>)}</tbody></table></div>{editing && <Editor value={editing.value} onClose={() => setEditing(null)} onSave={async value => { if (editing.id) await api.updateTitle(editing.id, value); else await api.createTitle(value); setEditing(null); await load(); }}/>}</div>;
}